name: Checks
on: [pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup node v15
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --ignore-engines --frozen-lockfile
      - name: Run tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
     
      - name: Comment PR 
        uses: thollander/actions-comment-pull-request@v1 
        env: 
          LOGS_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with: 
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
           message: | 
                Validation has passed!
                üîç Inspect the logs: ${{ env.LOGS_URL }}


  run-if-fail:
    if: ${{ always() && (needs.validation.result=='failure') }}
    needs: [validation]
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        env:
          LOGS_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           message: |
                ‚ùå Validation HAS FAILED
                üîç Inspect the logs: ${{ env.LOGS_URL }}
